name: Publish

on:
  workflow_dispatch:

jobs:
  version:
    name: Retrieve version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - id: version
      shell: bash
      run: |
        cargo generate-lockfile
        version="$(cargo pkgid | cut -d '#' -f2 | grep -o '[^:]*$')"
        if [ -z "${version}" ]; then
          echo "Invalid version number"
          exit 1
        fi
        echo "version=${version}" >> $GITHUB_OUTPUT
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  publish:
    needs: [test, version]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Dry-run package creation
      run: cargo package --no-verify
    - name: Create git tag
      env:
        version: ${{ needs.version.outputs.version }}
      run: |
        curl --location \
          --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/releases \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --data "{
              \"tag_name\":\"v${version}\",
              \"target_commitish\":\"${{ github.ref }}\",
              \"name\":\"v${version}\",
              \"draft\":false,
              \"prerelease\":false,
              \"generate_release_notes\":false
            }"
    - name: Publish
      run: cargo publish --no-verify --token "${CARGO_REGISTRY_TOKEN}"
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
